// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto

package com.coreos.jetcd.api;

public interface AuthRoleDeleteRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:etcdserverpb.AuthRoleDeleteRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string role = 1;</code>
   */
  String getRole();
  /**
   * <code>string role = 1;</code>
   */
  com.google.protobuf.ByteString
      getRoleBytes();
}
