// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto

package com.coreos.jetcd.api;

public interface AuthRoleGetResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:etcdserverpb.AuthRoleGetResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.etcdserverpb.ResponseHeader header = 1;</code>
   */
  boolean hasHeader();
  /**
   * <code>.etcdserverpb.ResponseHeader header = 1;</code>
   */
  com.coreos.jetcd.api.ResponseHeader getHeader();
  /**
   * <code>.etcdserverpb.ResponseHeader header = 1;</code>
   */
  com.coreos.jetcd.api.ResponseHeaderOrBuilder getHeaderOrBuilder();

  /**
   * <code>repeated .authpb.Permission perm = 2;</code>
   */
  java.util.List<com.coreos.jetcd.api.Permission> 
      getPermList();
  /**
   * <code>repeated .authpb.Permission perm = 2;</code>
   */
  com.coreos.jetcd.api.Permission getPerm(int index);
  /**
   * <code>repeated .authpb.Permission perm = 2;</code>
   */
  int getPermCount();
  /**
   * <code>repeated .authpb.Permission perm = 2;</code>
   */
  java.util.List<? extends com.coreos.jetcd.api.PermissionOrBuilder> 
      getPermOrBuilderList();
  /**
   * <code>repeated .authpb.Permission perm = 2;</code>
   */
  com.coreos.jetcd.api.PermissionOrBuilder getPermOrBuilder(
      int index);
}
