// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto

package com.coreos.jetcd.api;

public interface DefragmentRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:etcdserverpb.DefragmentRequest)
    com.google.protobuf.MessageOrBuilder {
}
