// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto

package com.coreos.jetcd.api;

public interface MemberAddResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:etcdserverpb.MemberAddResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.etcdserverpb.ResponseHeader header = 1;</code>
   */
  boolean hasHeader();
  /**
   * <code>.etcdserverpb.ResponseHeader header = 1;</code>
   */
  com.coreos.jetcd.api.ResponseHeader getHeader();
  /**
   * <code>.etcdserverpb.ResponseHeader header = 1;</code>
   */
  com.coreos.jetcd.api.ResponseHeaderOrBuilder getHeaderOrBuilder();

  /**
   * <pre>
   * member is the member information for the added member.
   * </pre>
   *
   * <code>.etcdserverpb.Member member = 2;</code>
   */
  boolean hasMember();
  /**
   * <pre>
   * member is the member information for the added member.
   * </pre>
   *
   * <code>.etcdserverpb.Member member = 2;</code>
   */
  Member getMember();
  /**
   * <pre>
   * member is the member information for the added member.
   * </pre>
   *
   * <code>.etcdserverpb.Member member = 2;</code>
   */
  com.coreos.jetcd.api.MemberOrBuilder getMemberOrBuilder();

  /**
   * <pre>
   * members is a list of all members after adding the new member.
   * </pre>
   *
   * <code>repeated .etcdserverpb.Member members = 3;</code>
   */
  java.util.List<Member>
      getMembersList();
  /**
   * <pre>
   * members is a list of all members after adding the new member.
   * </pre>
   *
   * <code>repeated .etcdserverpb.Member members = 3;</code>
   */
  Member getMembers(int index);
  /**
   * <pre>
   * members is a list of all members after adding the new member.
   * </pre>
   *
   * <code>repeated .etcdserverpb.Member members = 3;</code>
   */
  int getMembersCount();
  /**
   * <pre>
   * members is a list of all members after adding the new member.
   * </pre>
   *
   * <code>repeated .etcdserverpb.Member members = 3;</code>
   */
  java.util.List<? extends com.coreos.jetcd.api.MemberOrBuilder> 
      getMembersOrBuilderList();
  /**
   * <pre>
   * members is a list of all members after adding the new member.
   * </pre>
   *
   * <code>repeated .etcdserverpb.Member members = 3;</code>
   */
  com.coreos.jetcd.api.MemberOrBuilder getMembersOrBuilder(
    int index);
}
