// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto

package com.coreos.jetcd.api;

public interface MemberUpdateResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:etcdserverpb.MemberUpdateResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.etcdserverpb.ResponseHeader header = 1;</code>
   */
  boolean hasHeader();
  /**
   * <code>.etcdserverpb.ResponseHeader header = 1;</code>
   */
  com.coreos.jetcd.api.ResponseHeader getHeader();
  /**
   * <code>.etcdserverpb.ResponseHeader header = 1;</code>
   */
  com.coreos.jetcd.api.ResponseHeaderOrBuilder getHeaderOrBuilder();

  /**
   * <pre>
   * members is a list of all members after updating the member.
   * </pre>
   *
   * <code>repeated .etcdserverpb.Member members = 2;</code>
   */
  java.util.List<com.coreos.jetcd.api.Member> 
      getMembersList();
  /**
   * <pre>
   * members is a list of all members after updating the member.
   * </pre>
   *
   * <code>repeated .etcdserverpb.Member members = 2;</code>
   */
  com.coreos.jetcd.api.Member getMembers(int index);
  /**
   * <pre>
   * members is a list of all members after updating the member.
   * </pre>
   *
   * <code>repeated .etcdserverpb.Member members = 2;</code>
   */
  int getMembersCount();
  /**
   * <pre>
   * members is a list of all members after updating the member.
   * </pre>
   *
   * <code>repeated .etcdserverpb.Member members = 2;</code>
   */
  java.util.List<? extends com.coreos.jetcd.api.MemberOrBuilder> 
      getMembersOrBuilderList();
  /**
   * <pre>
   * members is a list of all members after updating the member.
   * </pre>
   *
   * <code>repeated .etcdserverpb.Member members = 2;</code>
   */
  com.coreos.jetcd.api.MemberOrBuilder getMembersOrBuilder(
      int index);
}
