// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto

package com.coreos.jetcd.api;

public interface RequestOpOrBuilder extends
    // @@protoc_insertion_point(interface_extends:etcdserverpb.RequestOp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.etcdserverpb.RangeRequest request_range = 1;</code>
   */
  com.coreos.jetcd.api.RangeRequest getRequestRange();
  /**
   * <code>.etcdserverpb.RangeRequest request_range = 1;</code>
   */
  com.coreos.jetcd.api.RangeRequestOrBuilder getRequestRangeOrBuilder();

  /**
   * <code>.etcdserverpb.PutRequest request_put = 2;</code>
   */
  com.coreos.jetcd.api.PutRequest getRequestPut();
  /**
   * <code>.etcdserverpb.PutRequest request_put = 2;</code>
   */
  com.coreos.jetcd.api.PutRequestOrBuilder getRequestPutOrBuilder();

  /**
   * <code>.etcdserverpb.DeleteRangeRequest request_delete_range = 3;</code>
   */
  com.coreos.jetcd.api.DeleteRangeRequest getRequestDeleteRange();
  /**
   * <code>.etcdserverpb.DeleteRangeRequest request_delete_range = 3;</code>
   */
  com.coreos.jetcd.api.DeleteRangeRequestOrBuilder getRequestDeleteRangeOrBuilder();

  /**
   * <code>.etcdserverpb.TxnRequest request_txn = 4;</code>
   */
  com.coreos.jetcd.api.TxnRequest getRequestTxn();
  /**
   * <code>.etcdserverpb.TxnRequest request_txn = 4;</code>
   */
  com.coreos.jetcd.api.TxnRequestOrBuilder getRequestTxnOrBuilder();

  public com.coreos.jetcd.api.RequestOp.RequestCase getRequestCase();
}
