// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: auth.proto

package com.coreos.jetcd.api;

public interface RoleOrBuilder extends
    // @@protoc_insertion_point(interface_extends:authpb.Role)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes name = 1;</code>
   */
  com.google.protobuf.ByteString getName();

  /**
   * <code>repeated .authpb.Permission keyPermission = 2;</code>
   */
  java.util.List<com.coreos.jetcd.api.Permission> 
      getKeyPermissionList();
  /**
   * <code>repeated .authpb.Permission keyPermission = 2;</code>
   */
  com.coreos.jetcd.api.Permission getKeyPermission(int index);
  /**
   * <code>repeated .authpb.Permission keyPermission = 2;</code>
   */
  int getKeyPermissionCount();
  /**
   * <code>repeated .authpb.Permission keyPermission = 2;</code>
   */
  java.util.List<? extends com.coreos.jetcd.api.PermissionOrBuilder> 
      getKeyPermissionOrBuilderList();
  /**
   * <code>repeated .authpb.Permission keyPermission = 2;</code>
   */
  com.coreos.jetcd.api.PermissionOrBuilder getKeyPermissionOrBuilder(
      int index);
}
