// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto

package com.coreos.jetcd.api;

public interface WatchRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:etcdserverpb.WatchRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.etcdserverpb.WatchCreateRequest create_request = 1;</code>
   */
  com.coreos.jetcd.api.WatchCreateRequest getCreateRequest();
  /**
   * <code>.etcdserverpb.WatchCreateRequest create_request = 1;</code>
   */
  com.coreos.jetcd.api.WatchCreateRequestOrBuilder getCreateRequestOrBuilder();

  /**
   * <code>.etcdserverpb.WatchCancelRequest cancel_request = 2;</code>
   */
  com.coreos.jetcd.api.WatchCancelRequest getCancelRequest();
  /**
   * <code>.etcdserverpb.WatchCancelRequest cancel_request = 2;</code>
   */
  com.coreos.jetcd.api.WatchCancelRequestOrBuilder getCancelRequestOrBuilder();

  public com.coreos.jetcd.api.WatchRequest.RequestUnionCase getRequestUnionCase();
}
